### PR TITLE
Hover card

### PR DESCRIPTION
**Pull request by sweeney-th**
I created a tooltip/hovercard and an on-click alert standing in for a redirect upon clicking a state

### CODE REVIEW

**Comment by grantstromgren** [comment]
Hey @sweeney-th looking good! One thing though is that I believe this hover shouldn't attach to the cursor, but attach near the state. We need a way for the hover over to pop up a new window and then allow the user to move the cursor within that area. If you check the prototype you can see roughly where the "More ->" link shows within the tooltip and is mouse clickable.

**Comment by sweeney-th** [comment]
Merged staging and fixed conflicts

**Comment by sweeney-th** [comment]
I added what I assumed was the linter the other branch was formatted using and resolved the conflicts. I also had to add the 'bootstrap' dependency. This is now working without conflicts. There is a warning in `_app.s` - "Parsing error: 'import' and 'export' may only appear at the top level" I assume people are aware of it however.

**Comment by grantstromgren** [comment]
@sweeney-th looking good! I'm expecting the box to remain up the entire time, right? When I mouse over a state it gives me the modal and it doesn't close if i mouse away from the modal/state?

Just making sure this is the behavior we want!

**Comment by sweeney-th** [comment]
> @sweeney-th looking good! I'm expecting the box to remain up the entire time, right?

I just made it so the user can click on things in the modal. I previously just had it so it followed the mouse to provide information. Now it detects if the mouse is within the modal so it can show information and also facilitate clicking on hyperlinks etc.

>When I mouse over a state it gives me the modal and it doesn't close if i mouse away from the modal/state?

I left the model there so the user would be able to select things from the modal. The modal will change with the state but remain stationary so the user can click things on it.

I was planning on adding some logic that deletes the modal when it's not on any state at all.

> Just making sure this is the behavior we want!

**Review by grantstromgren — APPROVED** [review]

**Pull request merged**
