### PR TITLE
Add cookies consent page

### LINKED ISSUE #218: Add cookie consent flow for Google Analytics

### PR DESCRIPTION
**Pull request by egiurleo**
Closes #218 

This PR adds a cookie consent screen when the user first lands on the map. It explains that this site uses cookies and lets the user accept or decline. If they accept, we'll use Google Analytics to track their usage of the site, and if not, Google Analytics will be disabled.

Screen Shot 2021-04-10 at 10 35 04 AM

### CODE REVIEW

**Comment by sarahgreen** [comment]
@egiurleo This looks great to me! @landonreed do you have time to review? (FYI – the actual Google Analytics implementation will be done in #119.)

**Review by sarahgreen — APPROVED** [review]

**Review by landonreed — COMMENTED** [review]
@egiurleo, generally this looks good, but I ran into a couple of high-level issues:
- when I click "Decline" and reload the page, I am greeted with the consent page again. I'm assuming we only want to show this once (per user/browser)
- If I navigate directly to http://localhost:3000/states/montana, I don't see the message. Would it be better to move this cookie initialization logic from `pages/index.js` to `pages/_app.js`?

**Comment by egiurleo** [comment]
@landonreed Oh interesting re: decline. Let me check that out! And yeah you're right on your second point.

**Comment by egiurleo** [comment]
@landonreed When I click "Decline" my page doesn't refresh! Tested with Safari and Chrome. What browser are you using/do you have any idea why that would be happening? 😓

**Comment by egiurleo** [comment]
@landonreed Turns out I thought I was writing Ruby and I didn't use the `return` keyword 🤦🏻‍♀️ If you try it again, it should work, and be on all pages now!

**Comment by sarahgreen** [comment]
FWIW – I can no longer replicate either of the issues Landon identified :)

**Review by landonreed — APPROVED** [review]
Looks good! I’m digging the method name changes, too!

**Pull request merged**
