### PR TITLE
Add loading state to forms

### LINKED ISSUE #191: Latency first time submitting a form – speed up or add a loading state?
The first time I submitted a form during my session, it took 24 seconds to successfully submit. This latency seems to be limited to the first time a form is submitted – I couldn't repro with second, third, fourth, etc form submissions.

### PR DESCRIPTION
**Pull request by egiurleo**
Closes #191.

This PR adds a loading state when you submit a form that says "Sending your response..." until the response succeeds or fails! Here's what it looks like:

Screen Shot 2021-04-03 at 12 53 25 PM

### CODE REVIEW

**Review by sarahgreen — COMMENTED** [review]
@egiurleo The screenshot you posted looks great but I can't repro on my local – when I try to submit a form I just get an error. Console says `Internal server error`. I restarted both the backend and frontend. Is there another step I'm missing?

**Comment by egiurleo** [comment]
@sarahgreen Uh oh! I'll look into it. Let me try to repro the error locally.

**Comment by sarahgreen** [comment]
@egiurleo Any luck repro'ing? I imagine it's something with my local...

**Review by DanielKim1 — APPROVED** [review]
:100:

**Comment by DanielKim1** [comment]
Oh shit I didn't read the comments, let me try to reproduce Sarah's error

**Comment by DanielKim1** [comment]
ok, yep, reproduced. i'll look for anything interesting
Screen Shot 2021-04-04 at 6 11 22 PM

**Comment by DanielKim1** [comment]
I don't see anything obviously wrong with the request sent
Screen Shot 2021-04-04 at 6 25 47 PM

**Comment by DanielKim1** [comment]
`status` is set to `{loading: false}` instead of `{loading: false, success: true}`:
Screen Shot 2021-04-04 at 6 31 10 PM
Race condition between the two `setStatus` calls, maybe?

**Comment by egiurleo** [comment]
@DanielKim1 I think you're right? When I switched the `setStatus` calls, it seems to have fixed the issue. Can you check locally and verify?

**Comment by DanielKim1** [comment]
I have no idea why that would fix the problem, but yep, that fixed the problem :+1:
Ah, computers.

**Comment by DanielKim1** [comment]
Oh I see 🤦
I'm guessing that unlike `setState`, `setStatus` doesn't merge the status objects.

If anyone's reading this in the future and dealing with the same bug, `setState` works like this:
```
setState({ key1: "value1" })
// state is { key1: "value1" }
setState({ key2: "value2" })
// state is { key1: "value1", key2: "value2" }
```

but judging by how [status was set to {loading: false}](https://github.com/RagtagOpen/freefrom-map-frontend/pull/197#issuecomment-813109223), `setStatus` does _not_ merge the objects:
```
setStatus({ key1: "value1" })
// status is { key1: "value1" }
setStatus({ key2: "value2" })
// status is { key2: "value2" }
```

**Comment by sarahgreen** [comment]
@DanielKim1 @egiurleo I dunno what's going on with my local but I still get an `Internal server error` when I try to submit a form on this branch, even after restarting the app. Think it's just a blip and we should merge in, or something else going on?

**Comment by egiurleo** [comment]
@sarahgreen If I remember correctly it's been doing this for a while, right? I'm happy to get on a call this week and help debug! My backend locally is returning 200 👌🏻 

@DanielKim1 Thanks for catching that. I updated my code to only call `setStatus` once since it overwrites the whole object.

**Comment by sarahgreen** [comment]
@egiurleo Yeah the error I'm seeing is probably the same one from before. Let's go ahead and merge this one and I'll test on the live site!

**Review by sarahgreen — APPROVED** [review]

**Pull request merged**
