### PR TITLE
Add states list

### PR DESCRIPTION
**Pull request by landonreed**
This PR:
- adds the states list (not currently connected to back end data)
- restructures the layout of the index page
- resizes the map a bit to fit the layout
- fixes the hovercard blocking modal issue (#81) -- sorry didn't realize I was addressing a pre-existing issue!

Note: this PR is currently based on #89. Here's a [quick link to the commit range included in this PR](https://github.com/RagtagOpen/freefrom-map-frontend/pull/94/files/ba81e5aed1a421320b5c59f44cf9a7c36dce47d6..6fb39382c7b8e73c0cbb00de681ec839dfaa65fa).

### Screenshot of changes
image

### CODE REVIEW

**Comment by sarahgreen** [comment]
Someone else should do a code review, since I was just reviewed for UX, but I think it's looking really good @landonreed!

A couple small things –
I think a few more pixels of padding between the text and container would be helpful, both for each state in the list and the search bar.
Also, when the browser window is resized, the map cuts off and the page becomes horizontally scrollable rather than the map shrinking to keep its same dimensions proportionally to the page. Not sure if it'd be better to fix that now (if it relates to the positioning of the map with the list) or later.

state-list

**Comment by thadryanjs** [comment]
How does this look?
 
image

**Comment by sarahgreen** [comment]
@sweeney-th I like the padding, my only concern is the grade badge (e.g. "Little Accountability") shouldn't stretch. Its width was correct before.

**Comment by thadryanjs** [comment]
> @sweeney-th I like the padding, my only concern is the grade badge (e.g. "Little Accountability") shouldn't stretch. Its width was correct before.

Sorry I haven't the faintest idea what caused that! Here is how I have it now
image

**Comment by sarahgreen** [comment]
@sweeney-th @landonreed I think this looks good to merge in! Thank you both!

**Comment by egiurleo** [comment]
I merged some stuff into the base branch -- sorry for the conflicts! Let me know if you need help resolving them.

**Comment by landonreed** [comment]
No problem, @egiurleo. Just resolved them. For some reason my contributor agreement is still being flagged in the checks even though I signed it already. For some reason I'm seeing a "Server error 500" when I go to try to sign it again 😬. Not sure if that's a known issue...

**Comment by egiurleo** [comment]
@landonreed It might be an issue with opening the PR before you signed it. Hopefully it will be resolved in future PRs :)

**Pull request merged**
