### PR TITLE
Resize map and add zoom button

### LINKED ISSUE #109: Zoom buttons for the map

### LINKED ISSUE #173: Mobile display issues – map
On smaller screens, the map looks a bit janky – it's way zoomed in and doesn't have enough spacing with the legend.

**PROPOSAL: hide map and legend entirely on small screens. Ideally we'd still show them on mid-size (tablets).**

map bug - tablet

map bug - phone

### PR DESCRIPTION
**Pull request by thadryanjs**

### CODE REVIEW

**Comment by sarahgreen** [comment]
@sweeney-th Looks awesome!!! In terms of what's next, my suggestions:
1. When you zoom in and then zoom back out, the map zooms out further than the map originally was. As a result you end up with a lot of whitespace. I think it'd be nicer if the zoom just reverts to the previous position.
Video recording of what I mean here: https://user-images.githubusercontent.com/6788487/109459801-5c376180-7a14-11eb-95c3-db82bc15d6c2.mov

2. Stylistically the button should match the rest of the page, my recommendations (others should feel free to give a different opinion):
- White background
- 2px border-radius
- Text should fit within the box with no overflow
- 7px of internal padding
- Remove capitalization on Small States so button reads "Zoom to small states"
Zoom in

3. Ideally it would be nice for the button text to switch from "Zoom to small states" to something like "Zoom out to full map" once it's been clicked.
Zoom out

**Comment by sarahgreen** [comment]
@sweeney-th Not sure if you're looking for more feedback at this point, sorry if I'm overstepping... I took a peek and gotta say I prefer one zoom button, or else maybe one for zoom in and one for zoom out. I'm worried having a separate button for each small state won't be intuitive (the buttons don't directly say or show "zoom") and will take up more room on the UI than necessary.

Also still seeing some odd behavior when I attempt to zoom back out after zooming in – the map doesn't revert to its previous zoom level / positioning.

**Comment by thadryanjs** [comment]
Good catch on the resize - I just accidentally set it back to 1440 instead of 1040 so that's fixed now.

I made them all a button because it was what was in the mockup but I can put it back tomorrow.

**Comment by sarahgreen** [comment]
@sweeney-th Ah, so sorry, I can see how that was unclear! That mockup was just a random map image pulled off Google as a placeholder, which happened to have a little box for each of the smaller states. We should just have 1 zoom in/out button. Check out my previous comment in this PR for some styling suggestions – definitely open to your ideas too though.

And the zoom in/out resize looks good now, thanks!!

**Comment by thadryanjs** [comment]
I don't have strong feelings either way and it won't be hard to put it back so NBD. It did occur to me though - I think you're right it's not obvious they're zoom buttons - one options is we split the difference and put a badge/icon over them that says "Zoom to:" to let people know what's up. It would be a little more concise that "Zoom to Northeast" or whatever I had in there before. Or we could go one button but I think my original text was awkward ha. I'll put the single button for now and we can see if we want to try new things after we have an MVP?

**Review by sarahgreen — APPROVED** [review]
@sweeney-th LGTM, thanks for all the iterations!

**Comment by thadryanjs** [comment]
NP! Totally forgot about the comments up top or there would have been one fewer lol

**Review by sarahgreen — APPROVED** [review]

**Pull request merged**
