### PR TITLE
Add toggle map/list view for mobile (#56)

### LINKED ISSUE #56: Mobile toggle for map/list view on homepage
On small screens, we should default to only showing the list view of states. We should show a button to toggle into map view. This button should be hidden at larger screen sizes.
Mobile Homepage - List View
Mobile Homepage - Map View

### PR DESCRIPTION
**Pull request by landonreed**
This PR closes #56 by adding the map/list toggle button on mobile (any screen smaller than "medium").

Note: the width/height of the map is not scaling properly on mobile. Any ideas @sweeney-th?

image

### CODE REVIEW

**Review by sarahgreen — CHANGES_REQUESTED** [review]
@landonreed This is looking awesome! My only comment is that I think we should have the map vanish and be replaced by the toggle button as soon as it no longer fits next to the list. Right now there's an intermediary state when shrinking the browser window where the map gets pushed below the list and the toggle button doesn't appear yet. See video: https://drive.google.com/file/d/1DhPW8aYJEdSzlWMIgHOcqPhvd8sork0u/view?usp=sharing

**Comment by landonreed** [comment]
Good catch, @sarahgreen! Fixed in 0203bbef3ba890b8d22a8bdca0292bd34ffbe774!

**Comment by landonreed** [comment]
@sarahgreen, I just fixed some merge conflicts with `staging`. Do you think this is OK to merge now?

**Comment by sarahgreen** [comment]
@landonreed I'm good with merging it in, the toggle works nicely! I can file bug tickets related to the map positioning and the display of other page elements on small screens.

**Review by sarahgreen — APPROVED** [review]

**Review by egiurleo — APPROVED** [review]
This makes sense to me! Thank you for working on it.

**Pull request merged**
