### PR TITLE
Force push to heroku (#104)

### LINKED ISSUE #104: Git error when deploying to Heroku via heroku/deploy-via-git
The following error is occuring while deploying to Heroku:

```
To https://git.heroku.com/*********************.git
 ! [rejected]        staging -> main (non-fast-forward)
error: failed to push some refs to 'https://heroku:************************************@git.heroku.com/*********************.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Exited with code exit status 1
CircleCI received exit code 1
```

Based on [this discussion](https://discuss.circleci.com/t/deploying-circleci-changes-to-heroku-using-git/25210/4), Heroku does not clone the repo fresh each time, so I'm guessing our squash commits are messing up the local repo on heroku (or there's some other weirdness happening)? Using the `force` option might fix this (see [docs](https://circleci.com/developer/orbs/orb/circleci/heroku#commands-deploy-via-git)).

### PR DESCRIPTION
**Pull request by landonreed**
Closes #104. But I'm not 100% this is how the `force` option should be specified.

### CODE REVIEW

**Comment by DanielKim1** [comment]
Good find with that thread linked in #104 👍

I'm nervous about adding the force option to the config, though. How would you feel about manually running `git push heroku staging:main --force`, and seeing if that permanently fixes the issue?

Also, it appears that this PR by itself will not fix the deploys. #94 added back `package-lock.json` (i assume through git shenanigans), and Heroku will not deploy anything if both a `package-lock.json` and a `yarn.lock` file is present. I decided in #78 to choose yarn over npm, but it might not be too late to reverse the decision if you strongly prefer npm.

**Comment by landonreed** [comment]
I can definitely understand the nervousness with using `force` for anything! Based on what I found in the docs though, it seems like this parameter is only used during the following step. Based on that, it _seems_ safe, but I definitely understand the need to be cautious. I'm happy for others to weigh in and make the final call. (Also, I don't think I know the heroku URL to try the manual command).
```yaml
  - run:
      command: >
        if << parameters.force >>;then
          force="-f"
        fi


        heroku_url="https://heroku:$<< parameters.api-key >>@git.heroku.com/<<
        parameters.app-name >>.git"


        if [ -n "<< parameters.branch >>" ]; then
          git push $force $heroku_url << parameters.branch >>:main
        elif [ -n "<< parameters.tag >>" ]; then
          git push $force $heroku_url << parameters.tag >>^{}:main
        else
          echo "No branch or tag found."
          exit 1
        fi
```

**Comment by egiurleo** [comment]
Hi, all! I ran `git push heroku staging:main --force` and it seems to have fixed the issue for now! Are we okay with leaving this unmerged for now and seeing if the issue is fixed?

**Comment by landonreed** [comment]
Definitely! Thanks @egiurleo and @DanielKim1!

**Pull request closed without merging**
